# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-27 11:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_akun', models.CharField(choices=[('petugas', 'Petugas'), ('admin', 'Admin')], max_length=9)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrp', models.CharField(max_length=9)),
                ('nama', models.CharField(max_length=45)),
                ('alamat', models.TextField(blank=True)),
                ('no_telp', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_buku', models.CharField(max_length=10)),
                ('judul_buku', models.CharField(max_length=100)),
                ('pengarang', models.CharField(max_length=100)),
                ('jenis_buku', models.CharField(choices=[('kp', 'KP'), ('ta', 'TA'), ('bk', 'BK')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_pinjam', models.DateField()),
                ('tgl_kembali', models.DateField()),
                ('no_buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peminjaman.Buku')),
                ('nrp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peminjaman.Anggota')),
            ],
        ),
        migrations.CreateModel(
            name='Petugas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('jabatan', models.CharField(choices=[('admin', 'Admin'), ('petugas', 'Petugas')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='akun',
            name='petugas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peminjaman.Petugas'),
        ),
    ]
