# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-06 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anggota',
            name='foto',
            field=models.ImageField(blank=True, upload_to='D:\\TA\\perpustakaan\\assets/upload'),
        ),
        migrations.AlterField(
            model_name='buku',
            name='jenis_buku',
            field=models.CharField(choices=[('kp', 'Kerja Praktek'), ('ta', 'Tugas Akhir'), ('bk', 'Bimbing Konseling')], max_length=5),
        ),
    ]
