# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-06 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0002_auto_20160906_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='petugas',
            name='foto',
            field=models.ImageField(blank=True, upload_to='D:\\TA\\perpustakaan\\assets/upload'),
        ),
    ]
