# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-19 13:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0003_petugas_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='anggota',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('laki-laki', 'Laki-laki'), ('perempuan', 'Perempuan')], max_length=9),
        ),
        migrations.AddField(
            model_name='peminjaman',
            name='status',
            field=models.CharField(default=datetime.datetime(2016, 9, 19, 13, 56, 16, 979100, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buku',
            name='jenis_buku',
            field=models.CharField(choices=[('kp', 'Kerja Praktek'), ('ta', 'Tugas Akhir'), ('bi', 'Buku Ilmiah')], max_length=5),
        ),
    ]
