# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-30 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0005_remove_anggota_jenis_kelamin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjaman',
            name='no_buku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buku.Buku'),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='nrp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anggota.Anggota'),
        ),
        migrations.DeleteModel(
            name='Anggota',
        ),
        migrations.DeleteModel(
            name='Buku',
        ),
    ]
